type FoodEntry =
  | string
  | {
      name: string;
      aliases?: string[];
      tags?: string[];
      description?: string;
    };

const item = (
  name: string,
  aliases: string[] = [],
  tags: string[] = [],
  description?: string,
) => ({
  name,
  aliases,
  tags,
  description,
});

export const additionalFoodGroups = [
  {
    id: "group_mixed_noodle",
    slug: "mixed-noodle",
    name: "혼합면류",
    description: "칼국수, 냉면, 비빔국수처럼 건더기나 양념이 함께 있는 면류",
    sortOrder: 25,
  },
  {
    id: "group_chinese_blackbean_noodle",
    slug: "chinese-blackbean-noodle",
    name: "짜장면류",
    description: "짜장면, 간짜장처럼 춘장 소스가 들어간 중식 면류",
    sortOrder: 26,
  },
  {
    id: "group_pasta_sauced",
    slug: "pasta-sauced",
    name: "소스파스타류",
    description: "토마토, 오일, 로제 기반 파스타와 리조또",
    sortOrder: 27,
  },
  {
    id: "group_pasta_cream",
    slug: "pasta-cream",
    name: "크림파스타류",
    description: "크림, 치즈가 많이 들어가는 파스타와 리조또",
    sortOrder: 28,
  },
  {
    id: "group_broth_meal",
    slug: "broth-meal",
    name: "국물식사류",
    description: "곰탕, 국밥, 떡국처럼 국물과 건더기가 함께 있는 식사류",
    sortOrder: 29,
  },
  {
    id: "group_meat_dish",
    slug: "meat-dish",
    name: "육류반찬류",
    description: "불고기, 수육, 장조림 같은 육류 중심 반찬",
    sortOrder: 30,
  },
  {
    id: "group_spicy_stirfry",
    slug: "spicy-stirfry",
    name: "매운볶음류",
    description: "제육볶음, 닭갈비처럼 양념과 건더기가 많은 볶음류",
    sortOrder: 31,
  },
  {
    id: "group_rice_bowl",
    slug: "rice-bowl",
    name: "덮밥류",
    description: "덮밥, 카레, 오므라이스 같은 소스형 밥류",
    sortOrder: 32,
  },
  {
    id: "group_fried_rice",
    slug: "fried-rice",
    name: "볶음밥류",
    description: "볶음밥, 필라프처럼 재료가 섞인 밥류",
    sortOrder: 33,
  },
  {
    id: "group_cutlet",
    slug: "cutlet",
    name: "까스류",
    description: "돈까스, 생선까스처럼 튀김옷이 있는 메인 요리",
    sortOrder: 34,
  },
].map((group) => ({
  ...group,
  isFallbackGroup: false,
}));

export const additionalFoodGroupTags = [
  ["group_mixed_noodle", "tag_processed"],
  ["group_mixed_noodle", "tag_chunky"],
  ["group_chinese_blackbean_noodle", "tag_processed"],
  ["group_chinese_blackbean_noodle", "tag_chunky"],
  ["group_pasta_sauced", "tag_chunky"],
  ["group_pasta_cream", "tag_chunky"],
  ["group_pasta_cream", "tag_dairy"],
  ["group_broth_meal", "tag_chunky"],
  ["group_meat_dish", "tag_processed"],
  ["group_spicy_stirfry", "tag_spicy"],
  ["group_spicy_stirfry", "tag_chunky"],
  ["group_rice_bowl", "tag_processed"],
  ["group_rice_bowl", "tag_chunky"],
  ["group_fried_rice", "tag_processed"],
  ["group_fried_rice", "tag_chunky"],
  ["group_cutlet", "tag_fried"],
  ["group_cutlet", "tag_processed"],
  ["group_cutlet", "tag_chunky"],
] as const;

export const bulkFoodCatalogs = [
  {
    prefix: "soft_protein_extra",
    groupId: "group_soft_protein",
    items: [
      item("온두부"),
      item("두부부침"),
      item("수란"),
      item("반숙계란"),
      item("계란국"),
      item("달걀국", ["계란탕"]),
      item("흰살생선"),
      item("대구살구이"),
      item("명태살구이"),
      item("닭안심"),
      item("닭안심구이"),
      item("닭가슴살스테이크"),
    ],
  },
  {
    prefix: "porridge_extra",
    groupId: "group_white_porridge",
    items: [
      item("닭죽"),
      item("소고기죽"),
      item("전복죽"),
      item("참치죽"),
      item("흰쌀미음"),
      item("쌀미음"),
    ],
  },
  {
    prefix: "bread_extra",
    groupId: "group_bread",
    items: [
      item("모닝빵"),
      item("버터롤"),
      item("토스트"),
      item("프렌치토스트"),
      item("바게트"),
      item("크루아상"),
      item("롤케이크"),
      item("스폰지케이크"),
      item("카스텔라"),
      item("마들렌"),
      item("머핀"),
      item("식빵토스트"),
      item("샌드위치빵"),
      item("브리오슈"),
      item("우유식빵"),
      item("베이글"),
    ],
  },
  {
    prefix: "snack_extra",
    groupId: "group_low_fiber_snack",
    items: [
      item("젤리"),
      item("컵젤리"),
      item("과일젤리"),
      item("바닐라푸딩"),
      item("초코푸딩"),
      item("밀크푸딩"),
      item("비스킷"),
      item("버터쿠키"),
      item("웨하스"),
      item("플레인쿠키"),
      item("소프트비스킷"),
      item("플레인케이크"),
      item("스낵과자"),
      item("카스타드"),
    ],
  },
  {
    prefix: "clear_noodle_extra",
    groupId: "group_clear_noodle",
    items: [
      item("소면"),
      item("온면"),
      item("온국수"),
      item("멸치국수"),
      item("멸치소면"),
      item("잔치소면"),
      item("우동사리"),
      item("국수사리"),
      item("쌀국수사리"),
      item("사누끼우동"),
      item("어묵우동"),
      item("미소우동"),
    ],
  },
  {
    prefix: "clear_liquid_extra",
    groupId: "group_clear_liquid",
    items: [
      item("탄산수"),
      item("생수"),
      item("보리음료"),
      item("맑은이온음료"),
      item("스포츠음료"),
      item("사과맑은주스"),
      item("오렌지주스", [], ["tag_red_purple"], "색이 진한 주스는 보수적으로 본다"),
      item("포도주스", [], ["tag_red_purple"], "색이 진해 검사 전에는 보수적으로 본다"),
    ],
  },
  {
    prefix: "china_black",
    groupId: "group_chinese_blackbean_noodle",
    items: [
      item("짜장면", ["자장면"]),
      item("간짜장"),
      item("삼선짜장"),
      item("유니짜장"),
      item("쟁반짜장"),
      item("옛날짜장"),
      item("볶음짜장"),
      item("사천짜장", [], ["tag_spicy"]),
      item("고추짜장", [], ["tag_spicy"]),
      item("해물짜장"),
      item("불짜장", [], ["tag_spicy"]),
      item("짜장밥"),
    ],
  },
  {
    prefix: "china_spicy",
    groupId: "group_spicy_soup",
    items: [
      item("짬뽕"),
      item("삼선짬뽕"),
      item("해물짬뽕"),
      item("고기짬뽕"),
      item("고추짬뽕"),
      item("불짬뽕"),
      item("볶음짬뽕"),
      item("차돌짬뽕"),
      item("얼큰짬뽕"),
      item("짬뽕밥"),
      item("해물짬뽕밥"),
      item("마라짬뽕"),
    ],
  },
  {
    prefix: "pasta_sauced",
    groupId: "group_pasta_sauced",
    items: [
      item("스파게티"),
      item("파스타", ["스파게티"]),
      item("토마토파스타"),
      item("토마토스파게티"),
      item("로제파스타", [], ["tag_dairy"]),
      item("봉골레파스타"),
      item("알리오올리오"),
      item("명란파스타"),
      item("페스토파스타"),
      item("해물파스타"),
      item("새우파스타"),
      item("미트소스파스타"),
      item("볼로네제파스타"),
      item("미트볼파스타"),
      item("아라비아따", [], ["tag_spicy"]),
      item("나폴리탄"),
      item("토마토리조또"),
      item("로제리조또", [], ["tag_dairy"]),
      item("해산물리조또"),
      item("감바스파스타"),
      item("오일파스타"),
    ],
  },
  {
    prefix: "pasta_cream",
    groupId: "group_pasta_cream",
    items: [
      item("크림파스타"),
      item("까르보나라"),
      item("크림스파게티"),
      item("투움바파스타", [], ["tag_spicy"]),
      item("알프레도파스타"),
      item("새우크림파스타"),
      item("베이컨크림파스타"),
      item("치즈파스타"),
      item("크림리조또"),
      item("치즈리조또"),
      item("치킨크림파스타"),
      item("빠네파스타"),
    ],
  },
  {
    prefix: "broth_meal",
    groupId: "group_broth_meal",
    items: [
      item("설렁탕"),
      item("곰탕"),
      item("갈비탕"),
      item("닭곰탕"),
      item("삼계탕"),
      item("사골국"),
      item("사골떡국"),
      item("떡국"),
      item("떡만둣국"),
      item("북엇국"),
      item("황태국"),
      item("소고기무국"),
      item("무국"),
      item("어묵국"),
      item("오뎅국"),
      item("콩나물국밥", [], ["tag_vegetables_heavy"]),
      item("순대국"),
      item("돼지국밥"),
      item("소머리국밥"),
      item("해장국", [], ["tag_spicy"]),
      item("감자탕", [], ["tag_spicy"]),
      item("버섯전골", [], ["tag_vegetables_heavy"]),
      item("샤브샤브", [], ["tag_vegetables_heavy"]),
      item("육개장", [], ["tag_spicy", "tag_vegetables_heavy"]),
      item("사골만둣국", [], ["tag_processed"]),
    ],
  },
  {
    prefix: "meat_dish",
    groupId: "group_meat_dish",
    items: [
      item("불고기"),
      item("소불고기"),
      item("돼지불고기"),
      item("간장불고기"),
      item("갈비찜"),
      item("수육"),
      item("보쌈"),
      item("편육"),
      item("장조림"),
      item("함박스테이크"),
      item("스테이크"),
      item("갈비구이"),
      item("목살구이"),
      item("삼겹살"),
      item("훈제오리"),
      item("오리구이"),
      item("햄구이"),
      item("소시지구이"),
      item("생선구이"),
      item("연어구이"),
    ],
  },
  {
    prefix: "spicy_stirfry",
    groupId: "group_spicy_stirfry",
    items: [
      item("제육볶음"),
      item("닭갈비"),
      item("오징어볶음"),
      item("낙지볶음"),
      item("주꾸미볶음", ["쭈꾸미볶음"]),
      item("매운갈비찜"),
      item("고추장불고기"),
      item("순대볶음"),
      item("야채곱창"),
      item("곱창볶음"),
      item("돼지고기두루치기"),
      item("오삼불고기"),
      item("불닭"),
      item("닭발"),
      item("무뼈닭발"),
      item("오돌뼈"),
      item("양념게장"),
      item("김치볶음"),
      item("매운오뎅볶음"),
      item("떡갈비볶음"),
    ],
  },
  {
    prefix: "rice_bowl",
    groupId: "group_rice_bowl",
    items: [
      item("카레라이스", ["카레"]),
      item("오므라이스"),
      item("하이라이스"),
      item("규동"),
      item("부타동"),
      item("텐동"),
      item("스팸마요덮밥"),
      item("참치마요덮밥"),
      item("치킨마요덮밥", ["치킨마요"]),
      item("제육덮밥"),
      item("돈부리"),
      item("돈까스덮밥", ["가츠동"]),
      item("새우튀김덮밥"),
      item("소불고기덮밥"),
      item("오징어덮밥"),
      item("낙지덮밥"),
      item("회덮밥"),
      item("알밥"),
      item("장어덮밥"),
      item("연어덮밥"),
      item("계란덮밥"),
      item("새우덮밥"),
      item("소고기덮밥"),
      item("마파두부덮밥", [], ["tag_spicy"]),
      item("컵밥"),
      item("김치덮밥", [], ["tag_spicy"]),
      item("치즈카레"),
      item("닭갈비덮밥", [], ["tag_spicy"]),
      item("오므카레"),
      item("카레덮밥"),
    ],
  },
  {
    prefix: "fried_rice",
    groupId: "group_fried_rice",
    items: [
      item("볶음밥"),
      item("김치볶음밥", [], ["tag_spicy"]),
      item("새우볶음밥"),
      item("햄볶음밥"),
      item("치킨볶음밥"),
      item("야채볶음밥", [], ["tag_vegetables_heavy"]),
      item("계란볶음밥"),
      item("삼선볶음밥"),
      item("중화볶음밥"),
      item("마늘볶음밥"),
      item("필라프"),
      item("새우필라프"),
      item("치킨필라프"),
      item("버섯리조또", [], ["tag_vegetables_heavy"]),
      item("볶음짜장밥"),
    ],
  },
  {
    prefix: "mixed_noodle",
    groupId: "group_mixed_noodle",
    items: [
      item("칼국수"),
      item("해물칼국수"),
      item("닭칼국수"),
      item("바지락칼국수"),
      item("수제비"),
      item("비빔국수", [], ["tag_spicy"]),
      item("비빔면", [], ["tag_spicy"]),
      item("쫄면", [], ["tag_spicy"]),
      item("막국수", [], ["tag_spicy"]),
      item("물냉면"),
      item("비빔냉면", [], ["tag_spicy"]),
      item("냉면"),
      item("메밀국수", [], ["tag_whole_grain"]),
      item("소바", [], ["tag_whole_grain"]),
      item("판모밀", [], ["tag_whole_grain"]),
      item("라볶이", [], ["tag_spicy"]),
      item("볶음우동", [], ["tag_spicy"]),
      item("메밀소바", [], ["tag_whole_grain"]),
    ],
  },
  {
    prefix: "cutlet",
    groupId: "group_cutlet",
    items: [
      item("돈까스", ["돈가스", "돈카츠"]),
      item("치즈돈까스", ["치즈돈가스"]),
      item("생선까스"),
      item("새우까스"),
      item("안심까스"),
      item("치킨까스"),
      item("왕돈까스"),
      item("경양식돈까스"),
      item("고구마치즈돈까스"),
      item("카레돈까스"),
    ],
  },
  {
    prefix: "salad_extra",
    groupId: "group_salad",
    items: [
      item("그린샐러드"),
      item("양상추샐러드"),
      item("양배추샐러드"),
      item("치킨샐러드"),
      item("과일샐러드"),
      item("참치샐러드"),
      item("시저샐러드"),
      item("리코타샐러드", [], ["tag_dairy"]),
      item("단호박샐러드"),
      item("감자샐러드"),
    ],
  },
  {
    prefix: "namul_extra",
    groupId: "group_namul",
    items: [
      item("시금치나물"),
      item("콩나물무침"),
      item("고사리나물"),
      item("도라지무침"),
      item("취나물"),
      item("깻잎무침"),
      item("미역줄기볶음", [], ["tag_seaweed"]),
      item("버섯볶음"),
      item("브로콜리무침"),
      item("숙주나물"),
    ],
  },
  {
    prefix: "seeded_fruit_extra",
    groupId: "group_seeded_fruit",
    items: [
      item("블루베리"),
      item("체리"),
      item("자두"),
      item("파인애플"),
      item("오렌지", [], ["tag_with_peel"]),
      item("귤", [], ["tag_with_peel"]),
      item("천혜향", [], ["tag_with_peel"]),
      item("한라봉", [], ["tag_with_peel"]),
      item("석류"),
      item("블랙베리"),
      item("라즈베리"),
    ],
  },
  {
    prefix: "soft_fruit_extra",
    groupId: "group_soft_fruit",
    items: [
      item("복숭아", [], ["tag_with_peel"]),
      item("황도"),
      item("백도"),
      item("망고"),
      item("아보카도"),
    ],
  },
  {
    prefix: "seaweed_extra",
    groupId: "group_seaweed",
    items: [
      item("다시마"),
      item("파래"),
      item("톳"),
      item("매생이"),
      item("파래김"),
    ],
  },
  {
    prefix: "nuts_extra",
    groupId: "group_nuts",
    items: [
      item("캐슈넛"),
      item("피스타치오"),
      item("호박씨"),
      item("해바라기씨"),
      item("잣"),
      item("참깨"),
      item("깨"),
    ],
  },
  {
    prefix: "whole_grain_extra",
    groupId: "group_whole_grain",
    items: [
      item("귀리밥"),
      item("보리밥"),
      item("오곡밥"),
      item("퀴노아밥"),
      item("잡곡죽"),
      item("현미죽"),
      item("그래놀라", [], ["tag_nuts"]),
      item("시리얼"),
      item("콘플레이크"),
      item("뮤즐리", [], ["tag_nuts"]),
    ],
  },
  {
    prefix: "instant_noodle_extra",
    groupId: "group_stirfried_noodle",
    items: [
      item("신라면"),
      item("진라면"),
      item("너구리"),
      item("안성탕면"),
      item("짜파게티"),
      item("짜장라면"),
      item("크림진짬뽕", [], ["tag_dairy", "tag_spicy"]),
      item("까르보불닭볶음면", [], ["tag_dairy", "tag_spicy", "tag_fried"]),
      item("짜파구리"),
      item("볶음라면", [], ["tag_spicy"]),
      item("라면사리"),
      item("크림파스타라면", [], ["tag_dairy"]),
    ],
  },
  {
    prefix: "fastfood_extra",
    groupId: "group_fastfood",
    items: [
      item("치즈버거"),
      item("불고기버거"),
      item("새우버거"),
      item("치킨버거"),
      item("핫도그"),
      item("감자튀김"),
      item("치즈볼"),
      item("치킨너겟"),
      item("핫윙"),
      item("닭강정", [], ["tag_spicy"]),
      item("피자빵"),
      item("핫바"),
      item("소시지빵"),
      item("토르티야"),
      item("랩샌드위치"),
    ],
  },
] as const;
